# https://artifacthub.io/packages/helm/bitnami/mariadb
mariadb:
  architecture: standalone
  auth:
    existingSecret: mariadb-auth
  primary:
    podAnnotations:
      backup.velero.io/backup-volumes: data-mariadb-0
    persistence:
      storageClass: openebs-localpv-nvme
