# https://artifacthub.io/packages/helm/bitnami/mariadb
mariadb:
  architecture: standalone
  auth:
    existingSecret: mariadb-auth
  primary:
    persistence:
      storageClass: openebs-localpv-nvme
