global:
  repo: https://github.com/jbruns/ArgoCD-Talos.git
  branch: main
  domain: wavebe.am
  altDomainHome: bruns.house
  altDomainDev: deserialize.net
  altDomainRe: fi.re
  TZ: America/Los_Angeles

  applicationSets:
  - common
#  - media
#  - home
#  - monitoring
    
  storage:
    defaultClass: 
      name: openebs-localpv-default
      basePath: /var/mnt/openebs/default
    additionalClasses:
      openebs-localpv-nvme: /var/mnt/openebs/nvme
      openebs-localpv-hdd: /var/mnt/openebs/hdd

  metallb:
    defaultPool: 172.16.21.1-172.16.21.20
