{{- range $key, $val := $.Values.global.storage.additionalClasses }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ $key }}
  annotations:
    openebs.io/cas-type: local
    cas.openebs.io/config: |
      - name: StorageType
        value: "hostpath"
      - name: BasePath
        value: {{ $val | quote }}
provisioner: openebs.io/local
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---
{{- end }}
