# Create a single ArgoCD project to house all applications/ApplicationSets.
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd-talos
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: ArgoCD on Talos
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
