# https://github.com/openebs/openebs/blob/main/charts/values.yaml
openebs:
  # https://github.com/openebs/dynamic-localpv-provisioner/blob/HEAD/deploy/helm/charts/values.yaml
  localpv-provisioner:
     hostpathClass:
       name: '{{ .Values.global.storage.defaultClass.name }}'
       reclaimPolicy: Retain
       isDefaultClass: true
       basePath: '{{ .Values.global.storage.defaultClass.basePath }}'
  engines:
    replicated:
      mayastor:
        enabled: false

  zfs-localpv:
    zfsNode:
      encrKeysDir: /var/mnt/openebs
  