# https://artifacthub.io/packages/helm/bitnami/redis
redis:
  architecture: standalone
  auth:
    enabled: false
  master:
    podAnnotations:
      backup.velero.io/backup-volumes: redis-data-redis-master-0
    persistence:
      storageClass: openebs-localpv-nvme
